### ISSUE TITLE
Pierwsza wizja projektu graficznego

### ISSUE THREAD

**Issue by sigo** [rising-pixels/budget-planner#3]
### Do zrobienia

- [x] Umówić termin spotkania.
- [x] Omówić pierwsze założenia i wizję projektu graficznego.
- [x] Ustalić kolejne kroki.
- [x] Załączyć do zadania zaprezentowane projekty.

**Comment by LarussaDiana** [comment]
https://www.figma.com/file/U6sT2bCY6R3TQSnsNJnWDi/Budget-Planner-Ant-Design-System?type=design&node-id=179473-170394&t=e3Tm4lxOSF3BxFar-0

Pages w Figmie:
10.05.2023... - to wersja z dzisiaj. juz nie bede tam nic ruszała
xx.05.2023... - to bedzie kolejna wersja, po poprawkach od Mateusza
